### ISSUE TITLE
-webkit-image-set() might be a requirement to be compatible. 

### ISSUE THREAD

**Issue by karlcow** [whatwg/compat#144]
* Firefox [Support -webkit-image-set()](https://bugzilla.mozilla.org/show_bug.cgi?id=1709415)
* Firefox [implement image-set()](https://bugzilla.mozilla.org/show_bug.cgi?id=1107646)

GitHub shows some [usage of `-webkit-image-set()` only](https://github.com/search?l=CSS&o=desc&q=%5C-webkit-image-set&s=indexed&type=Code)

**Comment by karlcow** [comment]
* Chromium: [Issue 630597: Unprefix -webkit-image-set](https://bugs.chromium.org/p/chromium/issues/detail?id=630597)
* Webkit: [Support image-set() standard syntax ](https://bugs.webkit.org/show_bug.cgi?id=160934)
* [poll about image-set](https://twitter.com/bocoup/status/1130846782676541440) <img width="599" alt="Capture d’écran 2021-05-05 à 09 20 57" src="https://user-images.githubusercontent.com/505230/117084858-39625a00-ad83-11eb-96a0-26d55c1204c0.png">
* There is no usage counter on Blink [-webkit-image-set()](https://www.chromestatus.com/metrics/css/popularity) @foolip 


To watch out probably for Webkit ["image-src" support is missing. We only support "-webkit-image-src"](https://bugs.webkit.org/show_bug.cgi?id=159373)

**Comment by foolip** [comment]
Looks like the spec for this is https://drafts.csswg.org/css-images-4/#image-set-notation.

Should the prefixed variant be defined to behave exactly the same, or are there differences? @schenney-chromium do you know?

**Comment by schenney-chromium** [comment]
We would have a long road to remove the prefixed version because it is used in many Chrome and ChromeOS UI pages. Any change short of removing would also be challenging.

Fortunately, based on my understand of the parsing code and the spec, the -webkit-image-set spec is a syntactically valid subset of the image-set spec and the spec gives us a lot of scope in how to decide which image to use. So I don't see a need to adjust any spec based on back-compat and the implementation of image-set will be somewhat easier.

**Comment by emilio** [comment]
I think https://github.com/w3c/csswg-drafts/issues/6285 is the most trivial way to go forward with this in terms of complexity of both specifications and implementations.

**Comment by gsnedders** [comment]
This can be closed, as https://github.com/w3c/csswg-drafts/issues/6285 defined this in the CSS Images spec.

**Comment by miketaylr** [comment]
Awesome.
