### ISSUE TITLE
"Value: 	text "

### ISSUE THREAD

**Issue by CJKu** [whatwg/compat#46]
https://compat.spec.whatwg.org/#the-webkit-background-clip-property

> Value:​ 	text 
Not only text
webkit-background-clip: border-box | padding-box | content-box | text
background-clip: border-box | padding-box | content-box

**Comment by upsuper** [comment]
This issue is about the value syntax of `-webkit-background-clip`. As a prefixed version of `background-clip`, it should accept all values that `background-clip` already accepts, plus keyword `text` newly defined in this spec.

**Comment by miketaylr** [comment]
Ah, right. 

My plan before was to define `-webkit-background-clip: text` as a prefixed-only value, but obviously left out the other valid values.

Somewhat relevant (though not to fixing this issue as reported by @CJKu):

In https://lists.w3.org/Archives/Public/www-style/2016Mar/0305.html, @fantasai writes:

> the WG resolved on adding -webkit-background-clip: text to the
fill/stroke spec as an obsolete feature. But we didn't discuss adding
the unprefixed version.

@dholbert replied asking for clarification about the unprefixed style.

https://lists.w3.org/Archives/Public/www-style/2016Mar/0308.html
> (If the CSSWG doesn't intend for "background-clip:text" to be valid,
please provide clarification on how "-webkit-background-clip:text" would
be expected to have any effect at all... and how "background-clip" /
"-webkit-background-clip" should interact, since clearly they wouldn't
be true aliases in that case.)

I believe we plan on adding the unprefixed `background-clip` that accepts `text` in Gecko (with a pref), and Edge already supports it.

**Comment by dholbert** [comment]
> I believe we plan on adding the unprefixed background-clip
> that accepts text in Gecko (with a pref), and Edge already supports it.

That's basically correct, yes.

(Clarifying slightly: we've supported unprefixed `background-clip` with its standard accepted values for ages -- we're just adding a new value `text` to the list of values that we'll accept for that property, and that new value is guarded by a pref.)

**Comment by miketaylr** [comment]
Thanks @dholbert (and for the clarification).
